spring.application.name=rentcar-backend
spring.datasource.url=jdbc:mysql://localhost:3306/rent_car?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true