spring.application.name=rentcar-backend

# --- CONFIGURAZIONE SICURA PER GITHUB ---
spring.datasource.url=jdbc:mysql://${DB_HOST:mysql-1b2d5469-mmarrianna9-d34b.a.aivencloud.com}:${DB_PORT:17997}/${DB_NAME:defaultdb}?ssl-mode=REQUIRED
spring.datasource.username=${DB_USER:avnadmin}
# Lasciamo vuota o finta la password di default, la daremo a Render di persona!
spring.datasource.password=${DB_PASSWORD:INSERISCI_PASSWORD_SU_RENDER}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- IMPOSTAZIONI JPA ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect